export const EDIT_QUIZ_TEXT = {
  sectionTitle: "Redigera Quiz",
  updateButton: "Uppdatera Quiz",
  cancel: "Avbryt",
  loadError: "Kunde inte ladda quiz",
  updateError: "Ett fel uppstod vid uppdatering av quiz",
  loadingText: "Laddar quiz...",
  titleLabel: "Titel",
  titlePlaceholder: "Ange quiz-titel",
  descriptionLabel: "Beskrivning",
  descriptionPlaceholder: "Beskrivning av quizet (valfritt)",
  savedQuestionsTitle: (count: number) => `Sparade frågor (${count})`,
  questionForm: {
    addTitle: "Lägg till ny fråga",
    textLabel: "Frågetext",
    textPlaceholder: "Ange frågetext",
    correctAnswerLabel: "Rätt svar",
    yes: "Ja",
    no: "Nej",
    saveQuestion: "Spara fråga",
    updateQuestion: "Uppdatera fråga",
    editQuestionTitle: "Redigera fråga",
    saveChanges: "Spara ändringar",
    cancel: "Avbryt",
    clear: "Rensa",
    correctLabel: "Rätt svar:",
    edit: "Redigera",
    remove: "Ta bort",
  },
  validation: {
    questionRequired: "Frågetext är obligatorisk",
    titleRequired: "Titel är obligatorisk",
    minOneQuestion: "Du måste ha minst en fråga",
  },
} as const
