export const EDIT_QUIZ_TEXT = {
  sectionTitle: "Edit Quiz",
  updateButton: "Update Quiz",
  cancel: "Cancel",
  loadError: "Could not load quiz",
  updateError: "An error occurred while updating the quiz",
  loadingText: "Loading quiz...",
  titleLabel: "Title",
  titlePlaceholder: "Enter quiz title",
  descriptionLabel: "Description",
  descriptionPlaceholder: "Quiz description (optional)",
  savedQuestionsTitle: (count: number) => `Saved questions (${count})`,
  questionForm: {
    addTitle: "Add new question",
    textLabel: "Question text",
    textPlaceholder: "Enter question text",
    correctAnswerLabel: "Correct answer",
    yes: "Yes",
    no: "No",
    saveQuestion: "Save question",
    updateQuestion: "Update question",
    editQuestionTitle: "Edit question",
    saveChanges: "Save changes",
    cancel: "Cancel",
    clear: "Clear",
    correctLabel: "Correct answer:",
    edit: "Edit",
    remove: "Remove",
  },
  validation: {
    questionRequired: "Question text is required",
    titleRequired: "Title is required",
    minOneQuestion: "You must have at least one question",
  },
} as const
